name: recipie_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.0      
  firebase_core: ^3.1.0
  flutter_bloc: ^8.1.6
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
