// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-8hqSkkLUVTk9zNB2bI1rhsZBtyN_Dfk',
    appId: '1:635982574806:web:7b0ad57fc44f2834adc577',
    messagingSenderId: '635982574806',
    projectId: 'flutterrecipiea',
    authDomain: 'flutterrecipiea.firebaseapp.com',
    storageBucket: 'flutterrecipiea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehFSY_MdObuiBMZ97tJ2k3iE-nJClr2E',
    appId: '1:635982574806:android:be475a8daec5492eadc577',
    messagingSenderId: '635982574806',
    projectId: 'flutterrecipiea',
    storageBucket: 'flutterrecipiea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwXuLFbUbTqTdLZ6oLcvAY9Ju7JvlpMI',
    appId: '1:635982574806:ios:aaf34df214e25e73adc577',
    messagingSenderId: '635982574806',
    projectId: 'flutterrecipiea',
    storageBucket: 'flutterrecipiea.appspot.com',
    iosBundleId: 'com.example.recipieApp',
  );
}
